notes = {
    "permanent magnet materials": "iron, nickel, cobalt",
    "cause of magnetism": "moving electric charges/electrons",
    "compass": "earth is giant magnet; north-seeking end of compass needle points to magnetic north pole",
    "solenoid": "long coil of wire that gets magnetized",
    "electric charge si unit": "coulomb",
    "electric current si unit": "ampere",
    "electric potential si unit": "volt",
    "electric resistance si unit": "ohm",
    "electric power si unit": "watt",
    "electric energy si unit": "joule",
    "electric charge si unit": "coulomb",
    "galvanometer": "device that detects electric current",
    "conventional current flow": "positive -> negative",
    "power": "work/time or joules/second",
    "what do waves carry": "energy",
    "wave types": "transverse (perpendicular), longitudinal (parallel)",
    "shadow types": "umbra (self) + penumbra (cast)",
    "fusion occur on sun?": "yes, in the core",
    "our sun life cycle": "protostar -> main sequence -> red giant -> white dwarf (10 billion years)",
    "life cycle of star larger than sun": "protostar -> supergiant -> iron core collapse -> supernova -> remnant (neutron star of black hole) (few million years)",
    "life cycle of star smaller than sun": "protostar -> main sequence -> white dwarf (100 billion years?)",
    "what is the sun made of?": "hydrogen and helium",
    "main sequence hr diagram": "top left (hot + luminous) -> bottom right (cool + dim)",
    "alpha decay": "-> -2 protons -2 neutrons (He)",
    "beta decay": "-> +1 proton -1 electron -1 neutron",
    "gamma decay": "-> no change in nucleus",
    "concave": "real + virtual",
    "convex": "virtual",
    "focal length": "distance from lens to focal point",
    "focal point": "point where light rays converge",
    "magnets that can be magnetized": "ferromagnets",
    "what are elcteons": "tiny magnets, fields usually cancel eachother out",
    "magnetic poles": "north is south, south is north",
    "hans orsted electricity and magnetism": "electricity and magnetism are related",
    "solenoid": "long coil of wire that gets magnetized",
    "electromagnet": "solenoid with a current running through it + iron core",
    "measure and detect electric current": "galvanometer",
    "electromagnetic induction": "when a changing magnetic field induces an electric current in a conductor",
    "converts electrical energy into physical movement": "electric motor",
    "generator": "mechanical energy -> electrical energy",
    "changing electric fields cause": "eddy currents",
    "doppler effect": "change in frequency of sound due to motion between source or reciever",
    "doppler effect sound": "moving away -> lower frequency, moving towards -> higher frequency",
    "natural frequency": "frequency at which an object vibrates when it is disturbed",
    "resonance": "rocing object to vibrate at natural frequency",
    "device that amplifies sound": "sound board",
    "current of the ocean": "convection currents",
    "subduction zones": "plates go under eachother -> creates magma",
    "fault": "fracture in the earth's crust",
    "normal fault": "away",
    "reverse fault": "towards",
    "strike slip fault": "horizontal/parallel",
    "earthquake focus": "where the earthquake starts",
    "earthquake epicenter": "where it hit the crust",
    "record earthquake strength": "seismograph",
    "nucleon": "proton or neutron",
    "radioactivity": "spontaneous decay of unstable nuclei",
    "nuclear fusion": "combine (renewable)",
    "nuclear fission": "split (non-renewable)",
    "four fundamental forces": "in order (strong -> weak): strong, weak, electromagnetic, gravity",
    "strong force": "holds nucleus together",
    "weak force": "responsible for beta decay",
    "electromagnetic force": "responsible for holding atoms together",
    "gravity": "responsible for holding planets together",
    "non-harmful electromagnetic radiation": "visible light, radio waves, microwaves",
    "electromagnetic spectrum": "radio, microwaves, infrared, visible light, ultraviolet, x-rays, gamma rays",
    "fuel for nuclear fission": "uranium",
    "reactor core": "fuel rods, moderator, control rods, coolant",
    "moderator": "slows down neutrons (water)",
    "control rods": "absorb neutrons (usually boron)",
    "coolant": "heat -> steam -> turbine -> generator",
    "nuclear power plant": "fission -> heat -> steam -> turbine -> generator",
    "geiger counter": "detects ionizing radiation",
    "big bang": "universe started from a single point (red shift, microwave background, mixture of elements)",
    "white dwarfs": "stars that have exhausted their nuclear fuel - very small, very hot",
    "neutron stars": "stars that have collapsed into a single point - very dense, very hot",
    "black holes": "stars that have collapsed into a single point - very dense, very hot",
    "red dwarf": "small, cool, long life",
    "main sequence": "stable, fusion",
    "red shift": "light shifts to longer wavelengths (redder) - moving away from observer",
    "solar flares": "magnetic fields (get tangled) -> created from electricallty charged gasses -> generate elctric current",
    "eldctromagnetic radiation": "energy travels though space in the form of waves (bundles called photons)",
    "how does light travel?": "photon",
    "black holes": "gravity is so strong that nothing can escape",
    "massive objects time warp space": "time slows down as you get closer to the object",
    "what does mri use?": "strong magnetic fields",
    "what is heat?": "infrared radiation",
    "mineral that can absorb light": "fluorescent minerals",
    "types of waves in the sun": "all",
    "reflecton"
    "refracted light": "light that changes direction when it passes through a medium",
    "diffracted light": "light that spreads out when it passes through a medium",
    "polarized light": "light that vibrates in a single direction",
    "total internal reflection": "when higher -> lower (index of refraction) and theta > 90 -> total internal reflection",
    "frequency": "is pitch",
    "audible range": "20hz - 20000hz",
    "what determines loudness": "amplitude",
    "what is earth core made of?": "molten",
    "tectonic plates": "move slowly over time away from eachother",
    "what does magma do?": "pushes up when plates collide",
    "what do rocks do?": "move/bend with plates until strength is exceeded",
    "primary waves": "fastest, travel through solids/liquids/gas, compressional (parallel)",
    "secondary waves": "slower, travel through solids, transverse, shear (perpendicular)",
    "love and rayleigh waves": "travel below or on surface, slower than body waves, love side to side, rayleigh up and down",
    'earthquake wave order': "p, s, l, r",
    "quark flavors": "up, down, charm, strange, top, bottom",
    "cations": "positive ions",
    "anions": "negative ions",
    "what causes magnetism?": "pockets of electrons",
    "san andres fault": "strike-slip fault -> pacific plate and north american plate"
}